### PR TITLE
chore: move to CircleCI

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by jinwoo** [comment]
You have to turn on "Build forked pull requests" from Advanced Settings in CircleCI, in order to let it run builds for PRs.

**Comment by JustinBeckwith** [comment]
I can't turn it on :(  Who's repo admin?
image

**Comment by jinwoo** [comment]
@ofrobots Can you turn on "Build forked pull requests" for this repo?

@JustinBeckwith Why does Travis still run? Shouldn't that be removed with this PR?

**Comment by JustinBeckwith** [comment]
I'm now an admin on the repo.  I set it up to build forked PRs, and deleted the travis integration with the repo.  New PRs should get CircleCI now.

**Pull request merged**
