### PR TITLE
chore(package): update multipe dependencies

### PR DESCRIPTION
**Pull request by ofrobots**
* Upgrade to the latest gts.
* Fix import style to match gts.
* npm audit fix.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
If you want to support node.js 4, you're going to need to split out the `npm run check` step to only run on one version of node (8, 10, etc).

**Comment by ofrobots** [comment]
Yeah, I may need to either drop node 4, or change the `tsconfig.json` away from the default. The downstream dependency that will get affected is `google-auth-library` and looking at its [package.json](https://github.com/google/google-auth-library-nodejs/blob/0ff24c7c4a1c5da604dd2019dfc225a922934e3e/package.json#L7).

@JustinBeckwith are you ready to drop node 4 support from `google-auth-library`? I can move away from the default TS config if this is too early.

**Comment by JustinBeckwith** [comment]
Nah, go ahead. There's just no reason to keep support for 4 right now.

**Comment by ofrobots** [comment]
Next release will be semver major (3.0), but there is no imminent need to ship it.

**Pull request merged**
